In [1]:
import os
import numpy as np
from digits_net_infer import main

/home/abhishek/.local/lib/python3.5/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [2]:
main()

Reading the Config File..................
Reading the Config File Completed........

Reading Test Images.....................
Reading Test Images Completed...........

Preprocessing the data...................
Preprocessing of the data Completed......

Loading the Network.....................
Loading the Network Completed...........

Images shape : (10000, 1, 28, 28)
Labels shape : (10000, 1)

INFO:tensorflow:Restoring parameters from /home/abhishek/Desktop/deep_learning/computer_vision/digit_recognition_mnist/model_files_50/digits_model-50

Inference Started.......................
Inference Completed.....................
Time Taken for Inference : 1.7614200115203857

Accuracy Score of the model : 0.9879

Confusion Matrix for the prediction : 
[[ 977    0    0    1    0    0    0    0    0    2]
 [   0 1134    1    0    0    0    0    0    0    0]
 [   1    6 1018    1    0    0    0    4    1    1]
 [   0    3    3  998    0    3    0    0    2    1]
 [   0    0    0    0  977    0   